/* Utilizando a Função IFNULL */
SELECT
	C.NOME,
	IFNULL(C.EMAIL, 'NÃO TEM EMAIL') AS EMAIL,
	E.ESTADO,
	T.NUMERO
FROM
	CLIENTE C
INNER JOIN
	ENDERECO E
ON
	C.IDCLIENTE = E.ID_CLIENTE
INNER JOIN
	TELEFONE T
ON
	C.IDCLIENTE = T.ID_CLIENTE;